<a href="https://colab.research.google.com/github/SafaaMahbub/ds2002-fa26/blob/main/notebooks/05-etl-walmart/2026-10-16%20%E2%80%94%20Walmart%20Warm-Up%20SKU%20Mess%20%E2%80%94%20Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Walmart Warm-Up SKU Mess

**Lab — 2026-10-16 · Fall 2026**  

---

## Lab 08 — Walmart Warm-Up (SKU Mess)

This lab uses the **real midterm data** in `../06-midterm-walmart/data/`. It's a warm-up so you hit the ground running on the project. On Kaggle/Colab, upload the data folder or adjust the path.

*If the file isn't found, the cell falls back to a small inline sample so the notebook still runs.*

In [1]:
!git clone https://github.com/SafaaMahbub/ds2002-fa26.git

Cloning into 'ds2002-fa26'...
remote: Enumerating objects: 369, done.
remote: Counting objects: 100% (369/369), done.
remote: Compressing objects: 100% (337/337), done.
remote: Total 369 (delta 218), reused 23 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (369/369), 529.53 KiB | 7.46 MiB/s, done.
Resolving deltas: 100% (218/218), done.

In [2]:
import pandas as pd
PATH = '/content/ds2002-fa26/notebooks/06-midterm-walmart/data/product_catalog.csv'
try:
    cat = pd.read_csv(PATH)
except FileNotFoundError:
    from io import StringIO
    cat = pd.read_csv(StringIO('sku,product_name,category\nPT-12,pop-tarts strawberry,Breakfast Foods\nSKU#459812,Strawberry Pop-Tart,Breakfast\nPOPTART-STRAW,Pop-Tarts Strawberry,Breakfast'))
cat.head()

,sku,product_name,category,subcategory,unit_cost,supplier,package_size
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack

### Q1 — How many rows look like Pop-Tart products?

Filter on `product_name` containing `pop`, case-insensitively. Print the count and the matching rows.

In [3]:
# TODO (hint: .str.lower().str.contains('pop'))
pop =  cat[cat['product_name'].str.lower().str.contains('pop')]
print('count of pop-tart items is:',len(pop))
pop

count of pop-tart items is: 4

,sku,product_name,category,subcategory,unit_cost,supplier,package_size
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack

### Q2 — Which SKUs and names all mean *strawberry* Pop-Tart?

List them. Then note which Pop-Tart rows are **not** strawberry — those must stay separate, and saying so is part of the answer.

In [ ]:
# TODO

straw_pop =  cat[cat['product_name'].str.lower().str.contains('pop') & cat['product_name'].str.lower().str.contains('strawberry') ]

not_straw_pop =  cat[cat['product_name'].str.lower().str.contains('pop') & ~cat['product_name'].str.lower().str.contains('strawberry') ]

print('Strawberry poptarts:\n')
print(straw_pop[['sku','product_name']],'\n')

print('count of non strawberry pop-tart items is:',len(not_straw_pop))

print('\nNon-strawberry poptarts:')
not_straw_pop

Strawberry poptarts:

             sku          product_name
0          PT-12  pop-tarts strawberry
1     SKU#459812   Strawberry Pop-Tart
2  POPTART-STRAW  Pop-Tarts Strawberry
3  PT_STRAWBERRY  pop-tarts strawberry

count of non strawberry pop-tart items is: 0

Non-strawberry poptarts:

Empty DataFrame
Columns: [sku, product_name, category, subcategory, unit_cost, supplier, package_size]
Index: []

**Pop-Tart rows that are a different product:** there are no products that have a diffeen poptart flavor other than strawberry. All rows that are poptarts are of strawberry flavor and therefore the second print for the non-strawberry poptarts is empty.

### Q3 — Build the mapping

A dict from each variant SKU to one canonical SKU. Then apply it in a way that leaves unmapped SKUs as themselves rather than turning them into `NaN` — that single mistake silently deletes most of the catalog.

In [ ]:
# TODO
CANON = {
    'PT-12': 'POPTART-STRAW',
    'SKU#459812': 'POPTART-STRAW',
    'POPTART-STRAW': 'POPTART-STRAW',
    'PT_STRAWBERRY': 'POPTART-STRAW',
    # 'WTR-24':'WTR-24',
    # 'WATER24PK':'WTR-24',
    # 'WTR_24PK':'WTR-24',
    # 'BATT-100': 'BAT-AA4',
    # 'BAT-AA4':'BAT-AA4',
    # 'BATT_AA_4PK':'BAT-AA4',
    # 'BEER-24':'BEER-24',
    # 'LTBEER24':'BEER-24',
    # 'BG-MONO': 'BG-MONO',
    # 'GAME-MONO': 'BG-MONO',
    # 'MONOPOLY-01':'BG-MONO',
    # 'CARDS-01':'CARDS-01',
  	# 'PLAYCARD-STD':'CARDS-01',
    # 'STREAM-01':'STREAM-01',
    # 'ROKU-STD':'STREAM-01',
    # 'SOUP-CAN':'SOUP-CAN',
    # 'CNSOUP-01' : 'SOUP-CAN',
    # 'BREAD-WH':'BREAD-WH',
    # 'WHITEBREAD':'BREAD-WH',
    # 'PNUTBTR-16':'PB-16',
    # 'PB-16':'PB-16',
    # 'CNDL-EM':'CNDL-EM',
    # 'CANDLE-EMRG': 'CNDL-EM',
    # 'FAID-01':'FAID-01',
    # 'FIRSTAID-KIT':'FAID-01',
    # 'CHRG-PORT':'CHRG-PORT',
    # 'PORTCHARGER':'CHRG-PORT',
    # 'CHIPS-VP':'CHIPS-VP',
    # 'CHIPVARIETY': 'CHIPS-VP',
    # 'PTOWEL-6':'PTOWEL-6',
    # 'PAPERTOWEL6':'PTOWEL-6',
    # 'TOILETPAPER12':'TP-12',
    # 'TP-12':'TP-12',
    # 'DIAPERS-3':'DIAP-S3',
    # 'DIAP-S3':'DIAP-S3',
    # 'BABYFORMULA':'BFORM-01',
    # 'BFORM-01':'BFORM-01',
    # 'TARP-HD': 'HDTARP-01',
    # 'HDTARP-01':'HDTARP-01'
}

clean = cat.drop_duplicates().copy()                    # dedupe FIRST
clean = clean.assign(canonical=clean['sku'].map(CANON).fillna(clean['sku']))
print('rows:', len(cat), '->', len(clean))
print()
clean.head(5)

rows: 45 -> 45

,sku,product_name,category,subcategory,unit_cost,supplier,package_size,canonical
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack,POPTART-STRAW
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk,POPTART-STRAW
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack,POPTART-STRAW
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack,POPTART-STRAW
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack,WTR-24

There are 4 occcurences of the strawberry poptarts and I normalized them all to the same sku.

### Q4 — Normalize `category`

Strip and title-case, then show the distinct values before and after with counts. Note any pair that is still two labels for one thing — `Breakfast` and `Breakfast Foods` are not the same string but they are the same category.

In [ ]:
# TODO
catalog = pd.DataFrame({
    'sku': ['PT-12', 'SKU#459812', 'POPTART-STRAW', 'PT_STRAWBERRY',
            # 'WTR-24', 'WATER24PK', 'WTR_24PK', 'BATT-100', 'BAT-AA4',
            # 'BATT_AA_4PK', 'FLASH-01', 'LED-FLASH', 'BEER-24','LTBEER24',
            # 'BG-MONO', 'MONOPOLY-01', 'GAME-MONO','CARDS-01','PLAYCARD-STD',
            # 'STREAM-01', 'ROKU-STD', 'SOUP-CAN','CNSOUP-01', 'BREAD-WH',
            # 'WHITEBREAD', 'PB-16', 'PNUTBTR-16', 'CNDL-EM', 'CANDLE-EMRG',
            # 'FAID-01', 'FIRSTAID-KIT', 'CHRG-PORT','PORTCHARGER', 'CHIPS-VP',
            # 'CHIPVARIETY', 'PTOWEL-6', 'PAPERTOWEL6','TP-12', 'TOILETPAPER12',
            # 'DIAP-S3', 'DIAPERS-3', 'BFORM-01', 'BABYFORMULA', 'TARP-HD', 'HDTARP-01'
            ],
    'category':
            ['Breakfast Foods', 'Breakfast', 'Breakfast', 'breakfast',
            # 'Emergency Supplies', 'Emergency', 'Emergency', 'Emergency Supplies',
            # 'Emergency Supplies', 'Emergency', 'Emergency', 'EMERGENCY', 'Alcoholic Beverages',
            # 'ALCOHOL', 'ENTERTAINMENT', 'entertainment', 'ENTERTAINMENT', 'ENTERTAINMENT',
            # 'entertainment', 'Electronics', 'electronics', 'Groceries', 'GROCERY', 'Grocery',
            # 'grocery', 'GROCERY', 'GROCERY', 'EMERGENCY', 'EMERGENCY', 'health', 'health', 'ELECTRONICS',
            # 'ELECTRONICS', 'snacks', 'Snacks', 'household', 'HOUSEHOLD', 'household', 'Household', 'baby',
            # 'Baby Products', 'Baby', 'Baby', 'Emergency', 'emergency'

],
})

#Before normalization
print('BEFORE normalizing the categroy for the poptarts')
print(catalog['category'].value_counts(dropna=False))

# Use code to narrow it down: group by a normalized name and look for matches
catalog['normalized'] = (catalog['category'].str.lower()
                         .str.strip()
                         .str.title()
                         .replace({'Breakfast Foods': 'Breakfast'})
)

print("\nCategories AFTER cleaning:")
print(catalog['normalized'].value_counts(dropna=False))

candidates = (catalog.groupby('normalized')['sku']
              .agg(list).loc[lambda s: s.str.len() > 1])
candidates

BEFORE normalizing the categroy for the poptarts
category
Breakfast          2
Breakfast Foods    1
breakfast          1
Name: count, dtype: int64

Categories AFTER cleaning:
normalized
Breakfast    4
Name: count, dtype: int64

normalized
Breakfast    [PT-12, SKU#459812, POPTART-STRAW, PT_STRAWBERRY]
Name: sku, dtype: object

Before the normalization, there were 3 different variants on how to categories poptarts:breakfast,Breakfast, and Breakfast Foods. Since one of the sku has an additional word, I replaced 'Breakfast Foods' with 'Breakfast'.

### Q5 — Find the fragmentation you have not spotted yet

Hand-scanning a catalog does not scale. **TODO:** build a candidate list programmatically — normalize each product name (lowercase, strip punctuation, sort the words) and group by that, then show any group holding more than one SKU.

This is the workflow from Monday's lecture, and it is how you will actually approach the full catalog on the midterm.

In [ ]:
# TODO
clean['normalized_name'] = (clean['product_name'].str.lower()
                         .str.replace(r'[^a-z ]', ' ', regex=True)
                         .str.replace(r'\btarts?\b', 'tart', regex=True)
                         .str.split().apply(lambda w: ' '.join(sorted(w))))

candidates = (clean.groupby('normalized_name')['sku']
              .agg(list).loc[lambda s: s.str.len() > 1])
candidates

normalized_name
aa batteries pack                                 [BAT-AA4, BATT_AA_4PK]
aid first kit                                    [FAID-01, FIRSTAID-KIT]
beer light pack                                      [BEER-24, LTBEER24]
board game monopoly                    [BG-MONO, MONOPOLY-01, GAME-MONO]
bread white                                       [BREAD-WH, WHITEBREAD]
butter peanut                                        [PB-16, PNUTBTR-16]
candles emergency                                 [CNDL-EM, CANDLE-EMRG]
canned soup                                        [SOUP-CAN, CNSOUP-01]
cards playing                                   [CARDS-01, PLAYCARD-STD]
chips pack variety                               [CHIPS-VP, CHIPVARIETY]
duty heavy tarp                                     [TARP-HD, HDTARP-01]
flashlight led                                     [FLASH-01, LED-FLASH]
paper towels                                     [PTOWEL-6, PAPERTOWEL6]
pop strawberry tart    [PT-12, SKU#459812, POPTART-STRAW, PT_STRAWBERRY]
Name: sku, dtype: object

I used the steps that were taught us on mondays lecture. However, I had to add another replace statement so that any items that have tarts will be grouped together.

### Q6 — Prove the mapping is safe

**TODO:** assert that applying your mapping produced no nulls in the canonical column and did not change the number of rows. Consolidation renames; it never adds or removes.

In [ ]:
# TODO

assert clean['canonical'].notna().all()
len_before = len(clean)
assert len(clean) == len(cat.drop_duplicates())

print("pass")

pass

### Write-up

**a)** Name two product families beyond Pop-Tarts that appear fragmented, and how you would group them.

**b)** Where does consolidation stop being a data-cleaning task and become a business decision? Give one example from this catalog where you genuinely are not sure, and say who you would ask.

a) the bottled family seems to appear fragmented and they have three different variants of the sku: 'WTR-24', 'WATER24PK', 'WTR_24PK' and I would group them by mapping all 3 products to 'WTR-24'. Another product family that has several different skus is the battery AA family and they have 3 different skus: 'BATT-100', 'BAT-AA4', and 'BATT_AA_4PK'.I would group these three items to 'BAT-AA4' as they are basically the same product.

b)
I believe consolidation becomes a business decision rather than just a data cleaning tool when for example two products seem to be the same item but have differences in their supplier or price. For example, the beer family of two different rowa kind of had the same description  but the supplier was different so my question would be whether to merge them together because the products serve the same purpose. I would ask the manager whether the products should be treated the same or different for a specific analysis or if they should be tracked separately.